### ISSUE TITLE
License notice

### ISSUE THREAD

**Issue by senshu** [6004x/jade#1]
Hi and thanks for sharing this software.

I browsed the documentation at https://6004.mit.edu/ and the source tree in search for licensing information.

Is there a license file, or reference to an existing license, that I have missed?
If not, can you please provide details about the conditions for using your code?

**Comment by terman** [comment]
Hmm.  Looks like the link to the Terms of Use got lost on the website — it’s back
now.  And I’ve added the terms to the appropriate github repo.  Thanks for the
heads up.

- Chris

**Comment by senshu** [comment]
Thanks for reacting so quickly. I'm closing this issue.

**Comment by aidan-fitz** [comment]
It's still not there

**Comment by terman** [comment]
Actually the thread above was about the website for the course.  But I've just added a LICENSE file for the repo that explains the MIT license.
