### ISSUE TITLE
Reproducible disappearing elements

### ISSUE THREAD

**Issue by drhodes** [6004x/jade#5]
In chrome on linux,

1. select an any number of gate circuit elements
2. do gate level timing analysis
3. a timing analysis window pops up, close that window
4. move cursor slightly
5. *poof*, all the selected elements disappear.  

A mouse click anywhere on the grid will bring them back.

In firefox the behavior is slightly different.  Step 4 isn't required and although the elements disappear their terminal circles remain visible.

**Comment by terman** [comment]
Thanks for the test case!  I've tracked down the bug and pushed a fix but won't update the edX version until after the assignments just to be sure I don't mess up anyone's last minute push to finish up.
