### ISSUE TITLE
A decimal literal compromise

### ISSUE THREAD

**Issue by drhodes** [6004x/jade#6]
There was an idea about decimal literals in signal names.  Sometimes we get stuck in a false assumption thinking that `1010'8` means `0b00001010`, but is actually silently interpreted as one-thousand-and-ten.  A first glance might suggest that all decimal literals should use a `0d` prefix, like `0d10` to explicitly indicate the number `ten`.  After some consideration, it's clear that the proposed fix is heavy handed because of the prevalence of signals named like `A[31:0]`.

`A[0d31:0]` is too noisy, but here's a compromise.  Only signal names containing decimal literals with certain patterns of `1` and `0` would fall under scrutiny and be rejected as invalid.

unamiguous lits, like `[0, 1, 00, 000, 42, 31...]` would be accepted.
`[10, 11, 11110, ...]` would be rejected

Would this break too many schematics?  Thoughts?

**Comment by terman** [comment]
Jade uses the same literal prefix as many programming languages: by default numbers are decimal and a special prefix (0, 0b, 0x) is used to indicate a different base.  I think that going with a well-established and widely-used convention is probably preferable to using an ad-hoc convention that’s unique to Jade.

**Comment by drhodes** [comment]
Understood, thanks for the quick feedback.
